# Generated by Django 6.0.2 on 2026-02-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="uploads/")),
                (
                    "converted_file",
                    models.FileField(blank=True, null=True, upload_to="outputs/"),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "converted_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("word_to_pdf", "Word to PDF"),
                            ("pdf_to_word", "PDF to Word"),
                            ("image_convert", "Image Convert"),
                            ("qr_reader", "QR Reader"),
                        ],
                        max_length=50,
                    ),
                ),
                ("status", models.CharField(default="completed", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
