# Generated by Django 6.0.2 on 2026-02-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_userfile_file_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfile",
            name="file_type",
        ),
    ]
