# Generated by Django 6.0.2 on 2026-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_remove_userfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="tool_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
