# Generated by Django 6.0.2 on 2026-02-24 16:04

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_userfile_tool_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="converted_file",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.files.models.user_output_path
            ),
        ),
    ]
